name: .NET Publish

on:
  push:
    # branches: [ "master" ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet tool restore
        dotnet gitversion
        dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --output ./artifacts --configuration Release
    - name: Publish packages
      run: dotnet nuget push ./artifacts/**.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_TOKEN}} --skip-duplicate
